### ISSUE TITLE
Don't log tokens

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/k2k-proxy#35]
It's a security hazard

**Comment by knikolla** [comment]
Would logging them with LOG.debug instead be more acceptable?

**Comment by gsilvis** [comment]
That's better, but it's still a little scary, IMO.  Do you know if any other OpenStack service logs tokens at any debug level?

**Comment by knikolla** [comment]
Maps to https://bugs.launchpad.net/mixmatch/+bug/1640234
