### ISSUE TITLE
Use .get() on the Keystone session object, rather than pulling out the token and using requests manually.

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/k2k-proxy#38]

**Comment by knikolla** [comment]
Can you please paste some logs when trying with session.get?

**Comment by gsilvis** [comment]
Figured it out

**Comment by gsilvis** [comment]
I'll do this once search-auth is merged

**Comment by gsilvis** [comment]
.get throws an exception on a 404, apparently.  This makes it much less worth changing the code over.
