### ISSUE TITLE
Listener doesn't know that volumes can be moved between projects

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/k2k-proxy#45]
http://developer.openstack.org/api-ref-blockstorage-v2.html#os-vol-transfer-v2

When this API call is used, the volume will no longer be where the proxy has recorded it.

Hopefully there's some sort of notification when this action happens...

**Comment by gsilvis** [comment]
A notification is indeed generated:

https://github.com/openstack/cinder/blob/1a495922edf2ac3b18bfddce0b88dc52fec24e43/cinder/transfer/api.py#L222

**Comment by knikolla** [comment]
Resolved by #47
